programs/multisig/src/state.rs

Make the field `pub` so we could use it in account parsers

feat(permissions): make `mask` public

---

programs/multisig/src/lib.rs

Expose the `state` and `events` modules for when program is used as a dependency

expose state and events

---

sdk/multisig/src/instructions.ts
sdk/multisig/src/transactions.ts

Add `multisig.instructions.transactionExecute` to the SDK. Can be useful when developer just need a `TransactionInstruction` rather than a full `VersionedTransaction`.

feat(sdk): add transactionExecute instruction

---

programs/multisig/src/instructions/multisig_config.rs

We need to expose certain argument struct fields so the indexer can read the values appropriately

feat(args): expose fields

---

Anchor.toml
programs/multisig/src/instructions/proposal_create.rs
tests/index.ts
tests/suites/examples/immediate-execution.ts
tests/suites/multisig-sdk.ts
tests/utils.ts

Also refactor `multisig-sdk` tests so they don't work with shared global state and instead re-create the state in individual test suites.

Fail when creating proposal for stale transaction

---

programs/multisig/src/instructions/multisig_create.rs
sdk/multisig/idl/multisig.json
sdk/multisig/src/generated/instructions/multisigCreate.ts
sdk/multisig/src/rpc/multisigCreate.ts
tests/suites/multisig-sdk.ts
tests/utils.ts

Remove the "signer" flag from `create_key`.
We made `create_key` a signer originally in order to make sure no one is able to re-create the squad at the same address in case we allow deleting squads. 
We never added that feature though, so `create_key`  being a signer doesn't really get us anything. At the same time it slightly worsens composability of the program, because an extra signer always makes things harder for the caller.
@RohanKapurDEV This shouldn't affect our indexer, but adding you as a reviewer to double-check it.

feat(multisig_create): remove the 'signer' requirements from create_key

---

programs/multisig/src/instructions/batch_add_transaction.rs
programs/multisig/src/instructions/batch_create.rs
programs/multisig/src/instructions/config_transaction_create.rs
programs/multisig/src/instructions/proposal_create.rs
programs/multisig/src/instructions/vault_transaction_create.rs
sdk/multisig/idl/multisig.json
sdk/multisig/src/generated/instructions/batchAddTransaction.ts
sdk/multisig/src/generated/instructions/batchCreate.ts
sdk/multisig/src/generated/instructions/configTransactionCreate.ts
sdk/multisig/src/generated/instructions/proposalCreate.ts
sdk/multisig/src/generated/instructions/vaultTransactionCreate.ts
sdk/multisig/src/instructions/batchAddTransaction.ts
sdk/multisig/src/instructions/batchCreate.ts
sdk/multisig/src/instructions/configTransactionCreate.ts
sdk/multisig/src/instructions/proposalCreate.ts
sdk/multisig/src/instructions/vaultTransactionCreate.ts
sdk/multisig/src/rpc/batchAddTransaction.ts
sdk/multisig/src/rpc/batchCreate.ts
sdk/multisig/src/rpc/configTransactionCreate.ts
sdk/multisig/src/rpc/proposalCreate.ts
sdk/multisig/src/rpc/vaultTransactionCreate.ts
sdk/multisig/src/transactions/batchAddTransaction.ts
sdk/multisig/src/transactions/batchCreate.ts
sdk/multisig/src/transactions/configTransactionCreate.ts
sdk/multisig/src/transactions/proposalCreate.ts
sdk/multisig/src/transactions/vaultTransactionCreate.ts

This allows decoupling of the transaction creator from the account that pays fees for the account rent. 
Facilitates use-cases like transaction fees relayer and PDA creators

feat(instructions): add rent_payer account

---

README.md

Should this also include potential things users can do wrong (ex: send funds to multisig instead of vault)

Add footguns readme section

---

sdk/multisig/src/instructions/index.ts
sdk/multisig/src/instructions/multisigChangeThreshold.ts
sdk/multisig/src/transactions/index.ts
sdk/multisig/src/transactions/multisigChangeThreshold.ts

A few questions & confusions have came up lately regarding the "multisigChangeThreshold" being missing in the expected places, so I added and exposed it in both the "instructions" and "transactions" section

SDK: Expose "multisigChangeThreshold" in instructions and transactions

---

programs/squads_multisig_program/src/instructions/multisig_config.rs

While the invariant functionality in the multisig struct offers comprehensive coverage of state management, we're adding an additional check in the multisig_add_member functionality to explicitly check for duplicates. This helps insure that the member key must be removed before re-added (in the case of changing permissions for example), as the invariant check is not able to distinguish which key should be removed upon upon the invariant check.

Additional duplicate check for multisig_add_member

---

programs/squads_multisig_program/src/instructions/multisig_add_spending_limit.rs

In the case of a controlled multisig (via config_authority), the direct invocation of the multisig_add_spending_limit instruction does not sort the members being assigned to the spending_limit account (as it does in the normal autonomous multisig flow).
Here we add a sort() to insure that the invariant called at the end of the instruction will properly de-dedupe the Vec.

Sort members for spending limit via multisig_add_spending_limit

---

programs/squads_multisig_program/src/instructions/proposal_vote.rs
programs/squads_multisig_program/src/lib.rs
programs/squads_multisig_program/src/state/proposal.rs

Cancellation is blocked if new threshold exceeds space when proposal was first created. It's an edge case, but this will block the ability to cancel and thus reclaim rent. We propose adding a proposal_cancel_v2 for this specific realloc, but that requires a system_program  account, thus adding a new account context.

Cancelation realloc and current member state check/retain

---

programs/squads_multisig_program/src/instructions/config_transaction_execute.rs
programs/squads_multisig_program/src/instructions/multisig_add_spending_limit.rs
programs/squads_multisig_program/src/instructions/spending_limit_use.rs
sdk/multisig/idl/squads_multisig_program.json
tests/suites/examples/spending-limits.ts
tests/suites/multisig-sdk.ts

After dog-fooding Spending Limits both in Squads and Fuse and having a deep discussion with the protocol team, we suggest to drop the requirement for the Spending Limits to only be usable by the members of the multisig. 
This allows for perfectly valid workflows that are pretty clanky right now, for example creating an SL for the fee relayer (currently this requires adding the relayer as a member to the multisig with no permissions). 
The potential risks are dangling SLs that are created for random keys and now forgotten, but in our opinion it's a case for proper multisig housekeeping - making sure your SLs are up to date and deleted when not needed anymore

feat(spending_limits): allow spending limits for non-members

---

programs/squads_multisig_program/src/instructions/batch_execute_transaction.rs
programs/squads_multisig_program/src/instructions/vault_transaction_execute.rs
programs/squads_multisig_program/src/utils/executable_transaction_message.rs

* We convert seeds to a vec, only to be reduced/collected as a slice again. This would simply pass the slice originally.
* Ephemeral/signer seeds don't change per loop iteration, moved the logic outside of the loop.

Execute optimizations

---

sdk/multisig/package.json
sdk/multisig/tsconfig.json
yarn.lock

Some users of the SDK are blocked by a lack of exposed types & issues with ESM resolution. This should fix those issues
Tested with users who are blocked pinning this branch locally

SDK: fix esm resolution

---

sdk/multisig/package.json

Quick fix before the new version is shipped. `rimraf` is currently unused, and enforces a Node v20 as a minimum version
related to issue #116

SDK: remove rimraf

---

programs/squads_multisig_program/src/instructions/transaction_buffer_close.rs
programs/squads_multisig_program/src/state/spending_limit.rs

Based on Certora's preliminary findings, this fixes comments in the following files:
- `transaction_buffer_close.rs`
- `spending_limit.rs`

fix: comments from certora preliminary findings

---

programs/squads_multisig_program/src/instructions/transaction_buffer_close.rs
programs/squads_multisig_program/src/instructions/transaction_buffer_extend.rs

Fixes the seed constraints of the `transaction_buffer_close` instruction to allow the creator to close the account at any time.

Certora Audit Findings: Fix transaction_buffer_close seed constraints

---

programs/squads_multisig_program/src/instructions/transaction_buffer_close.rs
programs/squads_multisig_program/src/instructions/transaction_buffer_extend.rs

Fixes the seed constraints of the `transaction_buffer_close` instruction to allow the creator to close the account at any time.

Audit Findings: Fix transaction_buffer_close seed constraints

---

programs/squads_multisig_program/src/instructions/transaction_buffer_close.rs
programs/squads_multisig_program/src/instructions/transaction_buffer_create.rs
programs/squads_multisig_program/src/instructions/transaction_buffer_extend.rs
programs/squads_multisig_program/src/instructions/vault_transaction_create_from_buffer.rs
programs/squads_multisig_program/src/state/transaction_buffer.rs
sdk/multisig/idl/squads_multisig_program.json
sdk/multisig/src/generated/accounts/TransactionBuffer.ts
sdk/multisig/src/generated/types/TransactionBufferCreateArgs.ts
tests/suites/examples/transaction-buffer.ts
tests/suites/instructions/transactionBufferClose.ts
tests/suites/instructions/transactionBufferCreate.ts
tests/suites/instructions/transactionBufferExtend.ts
tests/suites/instructions/vaultTransactionCreateFromBuffer.ts

This PR includes the following commits:
- [0996f21 - refactor: lamport mutation into system transfer](https://github.com/Squads-Protocol/v4/commit/0996f21b1bec77c73dc1c2be44a37ca62c4af504)
- [ca85338 - feat: u8 for buffer seeding](https://github.com/Squads-Protocol/v4/commit/ca85338f6cfcfd619a1b4f5570f53d3d6d2d4335)
`0996f21` changes the original lamport mutation into a regular system transfer. The lamport mutation works, but its unclear why, when examining the runtime guarantee that program XYZ should only be able to borrow lamports from an account owned by program XYZ. In the original state we were able to borrow lamports from an account owned by the system program. The system transfer is safer, should the original behavior turn out to be unintended.
`ca85338` refactors the seed …

General Fixes

---

Cargo.lock
sdk/rs/Cargo.toml
sdk/rs/src/client.rs
sdk/rs/src/lib.rs

Since `multisig_create` has officially been removed in favor of `multisig_create_v2`, it needs to be removed from the SDK to fix build issues

fix(rs-sdk): remove deprecated multisig_create

---

README.md

Adds the link to the final Neodyme audit into `README.md`. 
Was meant to be included as part of  #142.

Update readme to include Neodyme audit link

---

cli/src/command/display_vault.rs
cli/src/command/mod.rs
cli/src/main.rs

Added a command to derive and show vault address by supplied squad base address and vault index.

feat(cli-vault): command show to vaults by index

---

sdk/multisig/src/utils.ts

Currently lookup table accounts must exist on-chain before `multisig.utils.accountsForTransactionExecute` can be called. 
This would allow passing accounts in locally before they exist on-chain.

@sqds/multisig: optional addressLookupTableAccounts arg for accountsForTransactionExecute

---

cli/Cargo.lock
cli/src/command/display_vault.rs
cli/src/command/mod.rs
cli/src/command/vault_transaction_execute.rs

This pull request introduces support for an additional signer keypair in the `VaultTransactionExecute` command, enhancing flexibility for transaction execution. The key changes include adding a new argument for the extra keypair, integrating it into transaction creation, and modifying the signing process.
Enhancements to transaction signing:
* [`cli/src/command/vault_transaction_execute.rs`](diffhunk://#diff-cf036f9931a37bfe66f225820436f9a2b0db8419963f3b570dec724298f94205R55-R57): Added a new argument `extra_keypair` to the `VaultTransactionExecute` struct, allowing users to specify an additional signer keypair.
* [`cli/src/command/vault_transaction_execute.rs`](diffhunk://#diff-cf036f9931a37bfe66f225820436f9a2b0db8419963f3b570dec724298f94205R70): Integrated the `extra_keypair` into the …

feat(cli): Add possibility to use an extra signer for vault tx execution
